### ISSUE TITLE
Movie and anime Sites

### ISSUE THREAD

**Issue by Km10110** [rippedpiracy/docs#1]
https://www.thewatchcartoononline.tv/ -Anime, superhero, etc  tv show site
https://sflix.to/- Movie, TV, and anime  show site

**Comment by kekkodance** [comment]
first site has been updated to https://www.wcofun.com/, the second site is down. Please check your sources before contributing.

**Comment by kekkodance** [comment]
nevermind, checking again the second site DOES work, removing the dash from the url.
