### ISSUE TITLE
Website translation

### ISSUE THREAD

**Issue by Myuui** [rippedpiracy/docs#106]
Add a translated version of ur page, like you unroll a menu to select a language

Could be in Spanish, German, French, Russian & Italian?

**Comment by Helmasko** [comment]
I don't see this happening, currently there too much text on the site for anyone to be interested in translating. Besides, the languages the maintainers (me an kekko) can actually translate to would be catering to a very insignificant percentage of viewers.

**Comment by kekkodance** [comment]
this seems like a literal issue of skill, the guide is meant for international users and is not catered to the cultures that those languages might have
