### ISSUE TITLE
Could this website have any e-mail contacts?

### ISSUE THREAD

**Issue by g-p-t-c** [rippedpiracy/docs#115]
I want contact the ripped piracy team by e-mail because I get ban on the ripped discord server yesterday without any reasons.I want contact the teams to know what rules I get touched and could I get unban on the server...
But looks like there are not any e-mail contacts that can contact the team...
I just wanna to receive the announcements of the ripped discord server...and being a nice pirate...
So are there any email addresses that can contact to the team?

**Comment by kekkodance** [comment]
Unfortunately, we don't have any email contacts publicly available. You were probably banned for having an account too new to be allowed in the server.
