### ISSUE TITLE
add websites

### ISSUE THREAD

**Issue by Chipsum** [rippedpiracy/docs#121]
Movies: Fmoviesz.to
Anime: Zorox.to, Anix.to
Manga: Mangafire.to

**Comment by kekkodance** [comment]
We added sites like Wotaku and The Index to take the burden of maintaining lots of questionable quality sites, this suggestion is redundant as (from what i've seen) the sites seem to be listed in there. If they're not, go make a PR at either Wotaku or The Index.

The movie site you listed here seems to have poor quality releases in it with ads cooked inside of the movies
