### ISSUE TITLE
Request to add Rave Game Search

### ISSUE THREAD

**Issue by IdleEndeavor** [rippedpiracy/docs#156]
Hello RippedPiracy Team,

I am the creator of [Rave Game Search](https://ravegamesearch.pages.dev). I would like to request the addition of it to the Games page of your website. I see that Rave Book Search has already been included, thank you very much for that.
I've recently updated the website to reflect all the latest changes of the r/piracy and r/piratedgames megathreads. Hence, it only indexes download sites that are confirmed safe by the community. It also has an improved filter for Repacks, Torrents and Direct downloads.

Cheers,
IdleEndeavor

**Comment by Helmasko** [comment]
Hello, I've had a look at the sites mentioned in your readme and found some issues. 

Firstly, there are many dead sites there, this doesn't bode well for how frequently updated it is, for potential malware risk carrying sites (software/games) this is very important.

Secondly our selection for software/games simply doesn't match with yours (neither does fmhy or piracy or piratedgames and we don't recommend those either for software/games) and we are very happy with our own selection and only that.

The decision is final, but good luck on your endeavours!
