### ISSUE TITLE
Sites to add

### ISSUE THREAD

**Issue by UA-Archiver** [rippedpiracy/docs#2]
Following listed sites are end point sites for the average user to enjoy the content on

Anime
https://animixplay.to/  Play anime from multiple popular sites, without ads and sync to MAL

Movies
https://soapgate.org/ (Soap2Day, link page, Movies and Shows to stream)
https://movies4discord.xyz (M4D, Stream + DDL, requires Discord registration to sign in)

Software
https://lrepacks.net Repacks of software

**Comment by TrumpetMonkey** [comment]
anime
https://9anime.id
https://zoro.to

manga
https://mangadex.org

movies
https://rinzry.stream

adobe software
https://w14.monkrus.ws/ (use translate extension)

apks
https://forum.mobilism.org

TrumpetMonkey#8658

**Comment by kekkodance** [comment]
@TrumpetMonkey next contributions, please make a seperate issue including everyone else thats about to make one.
