### ISSUE TITLE
[Suggestion] Since most of dodi's repacks have close to 0 seeders, add their discord link to the site

### ISSUE THREAD

**Issue by Killshot1337x** [rippedpiracy/docs#20]
Title .Their discord has a section for requesting reseeds of any torrent, can be useful for people looking to download older torrents, since
almost all of the DDL links are dead too.

**Comment by BearTS** [comment]
yes that would be great imo

**Comment by kekkodance** [comment]
I don't see how that could fit the site's category since thats something to ask to dodi himself. i would have to include all the discords available for every source we give.

**Comment by kekkodance** [comment]
in dodi's site the discord invite is very clear, so it would be kinda redundant adding it.
