### ISSUE TITLE
Music ripping discord bot

### ISSUE THREAD

**Issue by RouterCFW** [rippedpiracy/docs#24]
Games drive Discord sever with multiple bots to rip from deezer , tidal and qobuz

games drive server `https://discord.gg/82KuPtBHvH`
music bot server `https://discord.gg/qCCy5nmGKc`

**Comment by kekkodance** [comment]
the first invite is redundant, as the gamesdrive discord server is already linked in their site, the second discord invite is like one of the many already existing ripping bots for telegram/discord, there would be no reason to link that specific one.
