### ISSUE TITLE
FDM (download manager) yt-dlp add-on

### ISSUE THREAD

**Issue by salamturk** [rippedpiracy/docs#36]
I think you should add this addon to the ripped guide for FDM (free download manager) because it is a really useful addon (yt-dlp) which makes FDM able to download videos from over 1500+ sites.
name is **elephant**
**_https://github.com/meowcateatrat/elephant_**

**Comment by kekkodance** [comment]
prebuilt removed for safety reasons.

**Comment by salamturk** [comment]
> prebuilt removed for safety reasons.

understandable

**Comment by Helmasko** [comment]
Thank you for the contribution
