### ISSUE TITLE
How to configure AccurateRip when the key disc fails

### ISSUE THREAD

**Issue by Qlupic** [rippedpiracy/docs#37]
![image](https://user-images.githubusercontent.com/73070379/175914275-d50ad250-6e42-4aba-878a-d760ed343847.png)

The EAC [guide ](https://github.com/rippedpiracy/docs/blob/40b10f1a1ccd8dead8eeab8b66dd58e23f7081c4/Music/Ripping/EAC.md) fails to explain why the AccurateRip configuration is important and more importantly how to successfully configure it.

Some users [<sup>1</sup>](https://forum.dbpoweramp.com/showthread.php?16787-Endless-quot-Key-Disc-cannot-be-used-for-offset-detection-quot) [<sup>2</sup>](https://forum.dbpoweramp.com/showthread.php?23631-Key-Disc-cannot-be-used-for-offset-detection) [<sup>3</sup>](https://forums.stevehoffman.tv/threads/accurate-rip-key-disc-database.132078/) including myself got a message saying:

> This Key Disc cannot be used for offset detection it does not match the AccurateRip stored disc, or your drive does not exist in AccurateRip and this disc has multiple pressings stored. Please try a different Key Disc.

Some user claim to have tried 20 discs. 

- When the AccurateRip config fails, how can we bring back the window and retry?
- What should we expect in terms of how many discs we should we try? Not everybody has 20 discs available.
- Is there any disadvantage to skipping the Accurate Rip config?
- Is it possible to manually set the offset somehow, say for example if you find your drive in [this](http://accuraterip.com/driveoffsets.htm) list.

**Comment by kekkodance** [comment]
@doggo404

**Comment by kekkodance** [comment]
EOL.
