### ISSUE TITLE
Damn...

### ISSUE THREAD

**Issue by farawaycamera87** [rippedpiracy/docs#39]
Its just sad to see this happen I've been part of this amazing community for 2 or 3 months now and its just sad to see it go when i needed help i asked questions there and somebody would answer also thank you kekko and helmasko for helping me almost everytime

 R.I.P ripped.guide 

Also my discord and google account were disabled but im trying to get them back

-Cocolino

**Comment by kekkodance** [comment]
you won't get them back, fuck man...

**Comment by farawaycamera87** [comment]
> you won't get them back, fuck man...

Fuck then im gonna use an alt account for all of the shit im gonna sign up for

**Comment by farawaycamera87** [comment]
> you won't get them back, fuck man...

![Screenshot_20220729_142029.jpg](https://user-images.githubusercontent.com/110207347/181748594-8223a5f7-97c1-413a-99ba-a3d75360a9c0.jpg)

**Comment by farawaycamera87** [comment]
> Its just sad to see this happen I've been part of this amazing community for 2 or 3 months now and its just sad to see it go when i needed help i asked questions there and somebody would answer also thank you kekko and helmasko for helping me almost everytime
> 
> R.I.P ripped.guide
> 
> Also my discord and google account were disabled but im trying to get them back
> 
> -Cocolino

I will still crack games and things but i will do it on an alt account
