### ISSUE TITLE
New Discord Server?

### ISSUE THREAD

**Issue by farawaycamera87** [rippedpiracy/docs#40]
Maybe start an invite only discord server or only invite trusted members and then don't invite anyone or make a chat in the ripped.guide site cuz they can't take the site down can they?

**Comment by kekkodance** [comment]
As a wise man once said, you either do shit the right way or don't at all. We're not pussies, we lasted three years and would have lasted more by being completely open. Pirate Haven (our sister server) was termed too despite being private, in the RIAA scandal.

**Comment by kekkodance** [comment]
Reopened for awareness, others might ask without reading.

**Comment by farawaycamera87** [comment]
> As a wise man once said, you either do shit the right way or don't at all. We're not pussies, we lasted three years and would have lasted more by being completely open. Pirate Haven (our sister server) was termed too despite being private, in the RIAA scandal.

Eh i kinda agree

**Comment by snvoid** [comment]
> As a wise man once said, you either do shit the right way or don't at all. We're not pussies, we lasted three years and would have lasted more by being completely open. Pirate Haven (our sister server) was termed too despite being private, in the RIAA scandal.

Would you consider creating a server on divolt.xyz? There is a github repo here (https://github.com/ggtylerr/awesome-divolt)  for it as well with more information. Its a revolt fork where a bunch of these type of servers migrated to. The other option is matrix.

**Comment by kekkodance** [comment]
We would rather not. Many staff members (including me) are against the idea of making a new place for members to join, especially if it isn't Discord.
Unfortunately, you'll have to be on your own for support.
