### ISSUE TITLE
Current State of the Project

### ISSUE THREAD

**Issue by Helmasko** [rippedpiracy/docs#43]
As you guys may have heard, the Discord Server has recently been banned and as of now there are no plans on remaking it. Most of the already few Contributors that were working on the site have quit and this means updates to this guide will inevitably slow down.

I just want to say that being part of this community was probably the best thing that happened to me on Discord and I will continue to remember it that way.

As for the future of the project, I will continue to update it and seek for more knowledge to add to the guide, and especially now more than ever, any sort of help with GitHub issues and Pull Requests will be tremendously appreciated.

If anyone wants to contact me on Discord, my tag is HɛLmДsk∅#1010.

That's all, take care.

**Comment by farawaycamera87** [comment]
> As you guys may have heard, the Discord Server has recently been banned and as of now there are no plans on remaking it. Most of the already few Contributors that were working on the site have quit and this means updates to this guide will inevitably slow down.
> 
> I just want to say that being part of this community was probably the best thing that happened to me on Discord and I will continue to remember it that way.
> 
> As for the future of the project, I will continue to update it and seek for more knowledge to add to the guide, and especially now more than ever, any sort of help with GitHub issues and Pull Requests will be tremendously appreciated.
> 
> That's all, take care.

Thank you for everything you did and for staying after this ban

-cocolino

**Comment by emili22** [comment]
> As you guys may have heard, the Discord Server has recently been banned and as of now there are no plans on remaking it. Most of the already few Contributors that were working on the site have quit and this means updates to this guide will inevitably slow down.
> 
> I just want to say that being part of this community was probably the best thing that happened to me on Discord and I will continue to remember it that way.
> 
> As for the future of the project, I will continue to update it and seek for more knowledge to add to the guide, and especially now more than ever, any sort of help with GitHub issues and Pull Requests will be tremendously appreciated.
> 
> That's all, take care.

Nobody cares

**Comment by emili22** [comment]
> As you guys may have heard, the Discord Server has recently been banned and as of now there are no plans on remaking it. Most of the already few Contributors that were working on the site have quit and this means updates to this guide will inevitably slow down.
> 
> I just want to say that being part of this community was probably the best thing that happened to me on Discord and I will continue to remember it that way.
> 
> As for the future of the project, I will continue to update it and seek for more knowledge to add to the guide, and especially now more than ever, any sort of help with GitHub issues and Pull Requests will be tremendously appreciated.
> 
> That's all, take care.

What’s with this ‘statement’ about a dead channel. This delusional kid thought he was running an empire or smth smh

**Comment by MetaApo13** [comment]
I enjoyed my time in Ripped. Many best practices & ideas that I now recommend were actually takeaways from the helpful community at Ripped. 
It is sad to see such a vibrant & informative community go this way; it was one of the more resilient & better quality piracy servers out there. A big thank you to all the staff that worked tirelessly to make Ripped the great place it was. 
Regards, Maqbool.

**Comment by scurihd** [comment]
Thank you for Ripped. I really learned a lot and it was all thanks to this community. Everyone was helpful and I appreciated people taking their time to share their knowledge and advice. Many thanks.
-scuri

**Comment by RazvanRex** [comment]
# Thank you for everything, Ripped. 

I met a lot of awesome people that i still keep contact with , even today after 2 years since i first joined this community and learned lots of new things in it. 

Unfortunately i had some altercations with some of you guys in the past , but it was still awesome to be in here.

 It's sad to see it just end overnight.

**Comment by farawaycamera87** [comment]
> # Thank you for everything, Ripped. 
> 
> I met a lot of awesome people that i still keep contact with , even today after 2 years since i first joined this community and learned lots of new things in it. 
> 
> Unfortunately i had some altercations with some of you guys in the past , but it was still awesome to be in here.
> 
>  It's sad to see it just end overnight. 

2 ani?!?!

**Comment by RazvanRex** [comment]
> 2 years?!?!

yep, i first joined this 2 years ago lmao

**Comment by red0888** [comment]
Rest in Peace, an expected thing to have happened.
- Red.

**Comment by Helmasko** [comment]
If anyone wants to contact me for whatever reason, my tag is helmask0#5599.

**Comment by TaiAurori** [comment]
Morbius Monday giveth us back our Ripped. Thank you, based Michael Morbius.

**Comment by Helmasko** [comment]
well well well, Discord decided to actually listen to my appeal and guess we're back in business!

you can join through https://discord.gg/6qVr2aR
