### ISSUE TITLE
Blokada

### ISSUE THREAD

**Issue by ignoramous** [rippedpiracy/docs#63]
Might want to revisit [recommending](https://ripped.guide/Mobile/Android/) Blokada: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8536

They don't publish the app to F-Droid anymore out of spite. Besides, with Blokada 6, they've moved to cloud-based blocking (running on Google Cloud Platform the last I checked).

In case it helps, here's DivestOS recommended apps as reference: https://divestos.org/index.php?page=recommended_apps

Disclosure: I authored that merge request.

**Comment by kekkodance** [comment]
Thank you for your consideration. We have discussed this in the past and i fully agree with your opinion. Blokada used to be a good company but turned bad as soon as they made unique IDs for every single user running the app. I will be replacing it's entry tomorrow.

**Comment by kekkodance** [comment]
Done in https://github.com/rippedpiracy/docs/commit/3ca4c3e.
