### ISSUE TITLE
Suggestion to add Zotify

### ISSUE THREAD

**Issue by ghaithnotvertigo** [rippedpiracy/docs#70]
Zotify is a command line program like yt-dlp that downloads from spotify without going through any third party music providers, it pulls directly from spotify and has all the metadata too.

It is open source on gitlab - https://gitlab.com/team-zotify/zotify

**Comment by kekkodance** [comment]
done in https://github.com/rippedpiracy/docs/commit/32e26f162d4c801955964c355851814b1eb1c658.
