### ISSUE TITLE
Add Office Tool Plus

### ISSUE THREAD

**Issue by abUwUser** [rippedpiracy/docs#71]
Microsoft makes the download button hidden if you do not have a office license on your Microsoft account. [Office Tool Plus](https://otp.landian.vip/) is a program to download customizable Office packages, such as including Visio in the installer.

**Comment by kekkodance** [comment]
I personally don't like this tool since alternatives such as TechBench exist, don't know what Helmasko thinks of this

**Comment by abUwUser** [comment]
office tool plus is more powerful than techbench tbh. like for example, you can include various office products in a single install, without having to manually pack everything. other than having alternatives, is there any other reason as to you not like this tool?

**Comment by kekkodance** [comment]
i dislike their (probably) unreliable activation methods bundled in their app, and why bother adding all sorts of disclaimers when doing it yourself is way better
