### ISSUE TITLE
Sections suggestions android 

### ISSUE THREAD

**Issue by TheOfficialMohamed** [rippedpiracy/docs#73]
add Android Cracked/Modded App Markets

**Comment by kekkodance** [comment]
aaand which do you want us to add?

**Comment by abUwUser** [comment]
pov: he suggests aptoide

**Comment by TheOfficialMohamed** [comment]
Sites that download cracked or pirated applications for free or MOD (Unlimited Money) for applications, there are many, but I do not know who is safe

**Comment by kekkodance** [comment]
neither we do aside from mobilism and maybe an1, and we're surely not going on google to find out LMAO

tldr: this isn't a valid issue

**Comment by TheOfficialMohamed** [comment]
I'm sorry for the inconvenience, I didn't know
