### ISSUE TITLE
Add Ark to archive managers

### ISSUE THREAD

**Issue by abUwUser** [rippedpiracy/docs#80]
[Ark](https://apps.kde.org/ark/) is an archive manager made by the KDE team for Linux. All of the listed archive managers are only for Windows.

I might wanna consider adding GNOME's archive manager, tho i do not want to cog up the list

**Comment by Helmasko** [comment]
I'm not too sure we should add linux apps to our guide tbh. i feel like if we do, we'd have to do it properly and make a massive list which would unnecessarily make the misc section very long. also, most distros to my knowledge comes preinstalled with a file manager so this seems pointless.

**Comment by Helmasko** [comment]
just to add, im alright with linux apps here and there in piracy dedicated sections. But for misc section, if we're gonna add any 'cool' linux app we find, i feel the list will be too long. I can see it not being a big issue if we are stricter with what we add though, for example adding a file manager would def be unnecessary from my point of view, but adding a good file encryptor could be a good idea.

**Comment by abUwUser** [comment]
> also, most distros to my knowledge comes preinstalled with a file manager so this seems pointless.

some do, tho not at all have archive functionality, tbh the majority don't. for example, nautilus (GNOME's file explorer) has an extremely limited archive functionality (i mean, you double click the file and it automatically extracts)
