### ISSUE TITLE
Tool suggestions

### ISSUE THREAD

**Issue by FrenchGithubUser** [rippedpiracy/docs#83]
Hi, I am currently developping a tool for various websites. It is still under development, but a beta version is already available here : https://github.com/FrenchGithubUser/Hatt

Its goal is to support most trusted websites (if not every) which allows to download files via ddl or to stream them. Literally Jackett, but for ddl. 

Would it be possible to add it to a section ? I'm not sure in which section it would fit the best though, maybe the `Useful Apps` ?

**Comment by kekkodance** [comment]
we don't allow tools developed by the same people advertising them, this will allow you to change the src when we DO add the tool, possibly holding us liable for distributing unsafe tools. we also refrain from adding any "in development" software. you also do not list the sites that this tool searches from, and we're not willing to moderate for if you add unsafe sites to the tool.

**Comment by FrenchGithubUser** [comment]
I understand your point of view. No problem !

However, the sites used in this tool are listed at the bottom of the readme, and their configurations are in `assets/website_configs`
