### ISSUE TITLE
Missing newlines on Mobile/Android and on Mobile/iOS

### ISSUE THREAD

**Issue by abUwUser** [rippedpiracy/docs#86]
Newlines are missing at Mobile/Android and Mobile/iOS, as shown in the screenshot below. This was caused by #85 
![Screenshot from 2023-05-23 15-12-37](https://github.com/rippedpiracy/docs/assets/27961224/984593c5-bebd-483b-8714-124a329dcd5c)

**Comment by kekkodance** [comment]
...make a pr

**Comment by abUwUser** [comment]
> ...make a pr

done, although it would be better to leave as open, as when the PR gets merged it'll automatically close, if you're worried about that
