### ISSUE TITLE
qbittorrent.md (aka qbittorrent guide) in software - ripped has expired voucher

### ISSUE THREAD

**Issue by kablaziken** [rippedpiracy/docs#96]
i have tried the voucher ( that is paste'd below) like 2 times and both times they have been denied, citing that "its expired".
Windscribe 30GB Voucher
Free Until : Unknown
Key: СВОБОДА
https://windscribe.com/signup

**Comment by kablaziken** [comment]
in these pics
![firefox_cUt21wWClE](https://github.com/rippedpiracy/docs/assets/96533370/2baac7d6-aa39-4d7d-8729-9eee67a375d7)

![firefox_xWmgwTJ9Dv](https://github.com/rippedpiracy/docs/assets/96533370/bc924714-9b2b-42ad-9353-7ef2de756426)

**Comment by Helmasko** [comment]
I recommend you make a PR or an issue on https://gitlab.com/ZediAlreadyTaken/guides/-/tree/main, this is unrelated to us.
